name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-on-linux-with-jdk-21:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Build and test
        run: mvn clean verify --no-transfer-progress
