name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-on-linux-with-jdk-11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Build and test
        run: mvn clean verify --no-transfer-progress
